name: RSS Feed to CSV

on:
  schedule:
    # Run every day at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pandas
          
      - name: Fetch RSS and update CSV
        run: |
          python .github/scripts/rss_to_csv.py
        env:
          RSS_URL: 'https://www.gazzettaufficiale.it/rss/SG'
          CSV_PATH: 'data/gazzetta-update.csv'
          MAX_ENTRIES: 100
          
      - name: Commit and push changes
        run: |
          git config --global atomm 'GitHub Action'
          git config --global tommaso.agnoloni@gmail.com 'action@github.com'
          git add data/gazzetta-update.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update RSS feed data [skip ci]"
          git push
